repos:
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
      - id: cargo-check
      - id: clippy
  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: 5.11.4
    hooks:
      - id: isort

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: double-quote-string-fixer

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies: [
            'flake8-bugbear',
            'flake8-comprehensions',
            'flake8-mutable',
            'flake8-simplify',
            'flake8-pytest-style',
            'flake8-printf-formatting',
            'flake8-type-checking',
        ]

  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.19.2
    hooks:
      - id: check-github-actions
      - id: check-github-workflows

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: [ "--py36-plus", "--py37-plus", "--keep-runtime-typing" ]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
        additional_dependencies:
          - types-redis
          - pydantic
