[workspace]
members = [
    "self_limiters",
    "self_limiters_core",
]

[workspace.dependencies]
# TODO: Check if we can prune features here
tokio = { version = "^1.20.1", features=["time", "macros"]}
redis = { version = "^0.21.5" }
